// System Roles Constants
export const ROLES = {
  // System Roles
  SYSTEM: {
    SUPER_USER: "SU",
    AI_AGENT: "AI",
  },

  // Portal Roles
  PORTAL: {
    MEMBER: "MEMBER",
    NON_MEMBER: "NON-MEMBER",
  },

  // CRM Roles - Management Level
  CRM_MANAGEMENT: {
    GENERAL_SECRETARY: "GS",
    DEPUTY_GENERAL_SECRETARY: "DGS",
    DIRECTOR_INDUSTRIAL_RELATIONS: "DIR",
    ASSISTANT_DIRECTOR_INDUSTRIAL_RELATIONS: "ADIR",
    DIRECTOR_PROFESSIONAL_REGULATORY: "DPRS",
  },

  // CRM Roles - Officer Level
  CRM_OFFICERS: {
    MEMBERSHIP_OFFICER: "MO",
    ASSISTANT_MEMBERSHIP_OFFICER: "AMO",
    ACCOUNTS_MANAGER: "AM",
    DEPUTY_ACCOUNTS_MANAGER: "DAM",
    ACCOUNTS_ASSISTANT: "AA",
    INDUSTRIAL_RELATION_EXECUTIVE: "IRE",
    INDUSTRIAL_RELATIONS_OFFICERS: "IRO",
    INFORMATION_OFFICER: "IO",
    REGIONAL_OFFICER: "RO",
    BRANCH_OFFICER: "BO",
  },

  // CRM Roles - Specialized
  CRM_SPECIALIZED: {
    HEAD_LIBRARY_SERVICES: "HLS",
    LIBRARIAN: "LS",
    LIBRARY_ASSISTANT: "LA",
    COURSE_COORDINATOR: "CC",
    ASSISTANT_COURSE_COORDINATOR: "ACC",
  },

  // CRM Roles - Access Level
  CRM_ACCESS: {
    READ_ONLY: "REO",
  },
};

export const SAMPLE_ROLES = [
  {
    id: "SU",
    code: "SU",
    name: "Super User",
    description: "Full system access with all administrative permissions",
    tenantId: "tenant1",
    tenantName: "Main Organization",
    category: "SYSTEM",
    permissions: [
      "read:all",
      "user:read",
      "user:write",
      "user:delete",
      "user:create",
      "user:update",
      "user:list",
      "user:manage_roles",
      "role:read",
      "role:write",
      "role:delete",
      "role:create",
      "role:update",
      "role:list",
      "role:assign",
      "role:remove",
      "account:read",
      "account:write",
      "account:delete",
      "account:payment",
      "portal:access",
      "crm:access",
      "audit:read",
      "audit:write",
      "audit:delete",
    ],
    status: "active",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "AI",
    code: "AI",
    name: "AI Agent",
    description: "Automated system agent with limited administrative access",
    tenantId: "tenant1",
    tenantName: "Main Organization",
    category: "SYSTEM",
    permissions: [
      "user:read",
      "user:list",
      "account:read",
      "portal:access",
      "crm:access",
      "crm:member:read",
      "crm:member:list",
      "audit:read",
    ],
    status: "active",
    createdAt: "2024-01-15T10:15:00Z",
    updatedAt: "2024-01-15T10:15:00Z",
  },

  // Portal Roles
  {
    id: "MEMBER",
    code: "MEMBER",
    name: "Member",
    description: "Registered member with portal access",
    tenantId: "tenant1",
    tenantName: "Main Organization",
    category: "PORTAL",
    permissions: [
      "portal:access",
      "portal:profile:read",
      "portal:profile:write",
      "portal:dashboard:read",
      "portal:settings:read",
      "portal:notifications:read",
      "portal:documents:read",
      "portal:payments:read",
    ],
    status: "active",
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "NON-MEMBER",
    code: "NON-MEMBER",
    name: "Non-Member",
    description: "Non-member with limited portal access",
    tenantId: "tenant1",
    tenantName: "Main Organization",
    category: "PORTAL",
    permissions: [
      "portal:access",
      "portal:profile:read",
      "portal:profile:write",
      "portal:dashboard:read",
      "portal:settings:read",
    ],
    status: "active",
    createdAt: "2024-01-15T10:45:00Z",
    updatedAt: "2024-01-15T10:45:00Z",
  },

  // CRM Management Roles
  {
    id: "GS",
    code: "GS",
    name: "General Secretary",
    description: "Highest management level with full organizational access",
    tenantId: "tenant1",
    tenantName: "Main Organization",
    category: "CRM_MANAGEMENT",
    permissions: [
      "user:read",
      "user:write",
      "user:create",
      "user:update",
      "user:list",
      "role:read",
      "role:list",
      "account:read",
      "account:write",
      "account:payment",
      "portal:access",
      "crm:access",
      "crm:member:read",
      "crm:member:write",
      "crm:member:create",
      "crm:member:update",
      "crm:member:list",
      "crm:member:delete",
      "audit:read",
      "audit:write",
      "financial:read",
      "financial:write",
    ],
    status: "active",
    createdAt: "2024-01-15T11:00:00Z",
    updatedAt: "2024-01-15T11:00:00Z",
  },
  {
    id: "DGS",
    code: "DGS",
    name: "Deputy General Secretary",
    description:
      "Deputy management level with comprehensive organizational access",
    tenantId: "tenant1",
    tenantName: "Main Organization",
    category: "CRM_MANAGEMENT",
    permissions: [
      "user:read",
      "user:write",
      "user:create",
      "user:update",
      "user:list",
      "role:read",
      "role:list",
      "account:read",
      "account:write",
      "account:payment",
      "portal:access",
      "crm:access",
      "crm:member:read",
      "crm:member:write",
      "crm:member:create",
      "crm:member:update",
      "crm:member:list",
      "audit:read",
      "audit:write",
      "financial:read",
      "financial:write",
    ],
    status: "active",
    createdAt: "2024-01-15T11:15:00Z",
    updatedAt: "2024-01-15T11:15:00Z",
  },
  {
    id: "DIR",
    code: "DIR",
    name: "Director Industrial Relations",
    description: "Director level access for industrial relations management",
    tenantId: "tenant1",
    tenantName: "Main Organization",
    category: "CRM_MANAGEMENT",
    permissions: [
      "user:read",
      "user:write",
      "user:list",
      "account:read",
      "account:write",
      "portal:access",
      "crm:access",
      "crm:member:read",
      "crm:member:write",
      "crm:member:create",
      "crm:member:update",
      "crm:member:list",
      "crm:industrial:read",
      "crm:industrial:write",
      "crm:industrial:create",
      "crm:industrial:update",
      "audit:read",
    ],
    status: "active",
    createdAt: "2024-01-15T11:30:00Z",
    updatedAt: "2024-01-15T11:30:00Z",
  },

  // CRM Officer Roles
  {
    id: "MO",
    code: "MO",
    name: "Membership Officer",
    description: "Officer responsible for membership management and processing",
    tenantId: "tenant1",
    tenantName: "Main Organization",
    category: "CRM_OFFICERS",
    permissions: [
      "user:read",
      "user:list",
      "account:read",
      "account:write",
      "portal:access",
      "crm:access",
      "crm:member:read",
      "crm:member:write",
      "crm:member:create",
      "crm:member:update",
      "crm:member:list",
      "crm:application:read",
      "crm:application:write",
      "crm:application:create",
      "crm:application:update",
    ],
    status: "active",
    createdAt: "2024-01-15T12:00:00Z",
    updatedAt: "2024-01-15T12:00:00Z",
  },
  {
    id: "AMO",
    code: "AMO",
    name: "Assistant Membership Officer",
    description: "Assistant officer supporting membership operations",
    tenantId: "tenant1",
    tenantName: "Main Organization",
    category: "CRM_OFFICERS",
    permissions: [
      "user:read",
      "user:list",
      "account:read",
      "portal:access",
      "crm:access",
      "crm:member:read",
      "crm:member:write",
      "crm:member:create",
      "crm:member:update",
      "crm:member:list",
      "crm:application:read",
      "crm:application:write",
    ],
    status: "active",
    createdAt: "2024-01-15T12:15:00Z",
    updatedAt: "2024-01-15T12:15:00Z",
  },
  {
    id: "AM",
    code: "AM",
    name: "Accounts Manager",
    description: "Manager responsible for financial accounts and transactions",
    tenantId: "tenant1",
    tenantName: "Main Organization",
    category: "CRM_OFFICERS",
    permissions: [
      "user:read",
      "user:list",
      "account:read",
      "account:write",
      "account:payment",
      "account:transaction:read",
      "account:transaction:write",
      "financial:read",
      "financial:write",
      "invoice:create",
      "invoice:read",
      "invoice:update",
      "receipt:create",
      "receipt:read",
      "receipt:update",
      "portal:access",
      "crm:access",
      "crm:member:read",
      "crm:member:list",
    ],
    status: "active",
    createdAt: "2024-01-15T12:30:00Z",
    updatedAt: "2024-01-15T12:30:00Z",
  },
  {
    id: "IRO",
    code: "IRO",
    name: "Industrial Relations Officer",
    description: "Officer handling industrial relations and member support",
    tenantId: "tenant1",
    tenantName: "Main Organization",
    category: "CRM_OFFICERS",
    permissions: [
      "user:read",
      "user:list",
      "account:read",
      "portal:access",
      "crm:access",
      "crm:member:read",
      "crm:member:write",
      "crm:member:create",
      "crm:member:update",
      "crm:member:list",
      "crm:industrial:read",
      "crm:industrial:write",
      "crm:industrial:create",
      "crm:industrial:update",
    ],
    status: "active",
    createdAt: "2024-01-15T12:45:00Z",
    updatedAt: "2024-01-15T12:45:00Z",
  },

  // CRM Specialized Roles
  {
    id: "HLS",
    code: "HLS",
    name: "Head Library Services",
    description: "Head of library services with full library management access",
    tenantId: "tenant1",
    tenantName: "Main Organization",
    category: "CRM_SPECIALIZED",
    permissions: [
      "user:read",
      "user:list",
      "portal:access",
      "crm:access",
      "crm:member:read",
      "crm:member:list",
      "library:read",
      "library:write",
      "library:create",
      "library:update",
      "library:delete",
      "library:manage",
    ],
    status: "active",
    createdAt: "2024-01-15T13:00:00Z",
    updatedAt: "2024-01-15T13:00:00Z",
  },
  {
    id: "LS",
    code: "LS",
    name: "Librarian",
    description: "Librarian with library service management access",
    tenantId: "tenant1",
    tenantName: "Main Organization",
    category: "CRM_SPECIALIZED",
    permissions: [
      "user:read",
      "user:list",
      "portal:access",
      "crm:access",
      "crm:member:read",
      "crm:member:list",
      "library:read",
      "library:write",
      "library:create",
      "library:update",
    ],
    status: "active",
    createdAt: "2024-01-15T13:15:00Z",
    updatedAt: "2024-01-15T13:15:00Z",
  },
  {
    id: "CC",
    code: "CC",
    name: "Course Coordinator",
    description: "Coordinator responsible for course management and delivery",
    tenantId: "tenant1",
    tenantName: "Main Organization",
    category: "CRM_SPECIALIZED",
    permissions: [
      "user:read",
      "user:list",
      "portal:access",
      "crm:access",
      "crm:member:read",
      "crm:member:list",
      "course:read",
      "course:write",
      "course:create",
      "course:update",
      "course:manage",
    ],
    status: "active",
    createdAt: "2024-01-15T13:30:00Z",
    updatedAt: "2024-01-15T13:30:00Z",
  },

  // CRM Access Roles
  {
    id: "REO",
    code: "REO",
    name: "Read Only",
    description: "Read-only access for viewing system data",
    tenantId: "tenant1",
    tenantName: "Main Organization",
    category: "CRM_ACCESS",
    permissions: [
      "user:read",
      "user:list",
      "account:read",
      "portal:access",
      "crm:access",
      "crm:member:read",
      "crm:member:list",
      "audit:read",
    ],
    status: "active",
    createdAt: "2024-01-15T13:45:00Z",
    updatedAt: "2024-01-15T13:45:00Z",
  },
];

export const SAMPLE_TENANTS = [
  { id: "39866a06-30bc-4a89-80c6-9dd9357dd453", name: "Main Organization" },
  { id: "39866a06-30bc-4a89-80c6-9dd9357dd453", name: "Audit Department" },
  // { id: "68c873a5a4fc86b2dedd9ff5", name: "Finance Division" },
  // { id: "68c873a5a4fc86b2dedd9ff5", name: "HR Department" },
];

export const ROLE_STATUSES = [
  { value: "all", label: "All Statuses" },
  { value: "active", label: "Active" },
  { value: "inactive", label: "Inactive" },
  // { value: "suspended", label: "Suspended" },
];

export const getAllRolesList = () => {
  return SAMPLE_ROLES;
};

export const getTenantsList = () => {
  return SAMPLE_TENANTS;
};

export const getRolesByCategory = () => {
  return {
    SYSTEM: SAMPLE_ROLES.filter((role) => role.id === "SU" || role.id === "AI"),
    PORTAL: SAMPLE_ROLES.filter(
      (role) => role.id === "MEMBER" || role.id === "NON-MEMBER"
    ),
    CRM_MANAGEMENT: SAMPLE_ROLES.filter((role) =>
      ["GS", "DGS", "DIR", "ADIR", "DPRS"].includes(role.id)
    ),
    CRM_OFFICERS: SAMPLE_ROLES.filter((role) =>
      ["MO", "AMO", "AM", "DAM", "AA", "IRE", "IRO", "IO", "RO", "BO"].includes(
        role.id
      )
    ),
    CRM_SPECIALIZED: SAMPLE_ROLES.filter((role) =>
      ["HLS", "LS", "LA", "CC", "ACC"].includes(role.id)
    ),
    CRM_ACCESS: SAMPLE_ROLES.filter((role) => role.id === "REO"),
  };
};

export const ROLE_CATEGORIES = [
  { value: "SYSTEM", label: "system Roles" },
  { value: "PORTAL", label: "portal Roles" },
  { value: "CRM_MANAGEMENT", label: "CRM Management" },
  { value: "CRM_OFFICERS", label: "CRM Officers" },
  { value: "CRM_SPECIALIZED", label: "CRM Specialized" },
  { value: "CRM_ACCESS", label: "CRM Access" },
];
