export const SAMPLE_USERS = [
  {
    _id: "user1",
    tenantId: "tenant1",
    userEmail: "john.doe@organization.com",
    userFirstName: "John",
    userLastName: "Doe",
    userFullName: "John Doe",
    userMobilePhone: "+1234567890",
    userMemberNumber: "MEM001",
    userMicrosoftId: "microsoft-id-001",
    userAuthProvider: "microsoft",
    userSubject: "sub-001",
    userAudience: "aud-001",
    userIssuer: "iss-001",
    userIssuedAt: 1640995200,
    userAuthTime: 1640995200,
    userTokenVersion: "1.0",
    userPolicy: "B2C_1_signupsignin",
    userType: "CRM",
    userLastLogin: "2024-01-15T10:30:00Z",
    roles: [
      { _id: "role1", name: "General Secretary", category: "CRM_MANAGEMENT" },
      { _id: "role2", name: "Super User", category: "SYSTEM" },
    ],
    isActive: true,
    createdBy: "system",
    updatedBy: "admin",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    _id: "user2",
    tenantId: "tenant1",
    userEmail: "jane.smith@organization.com",
    userFirstName: "Jane",
    userLastName: "Smith",
    userFullName: "Jane Smith",
    userMobilePhone: "+1234567891",
    userMemberNumber: "MEM002",
    userMicrosoftId: "microsoft-id-002",
    userAuthProvider: "microsoft",
    userSubject: "sub-002",
    userAudience: "aud-002",
    userIssuer: "iss-002",
    userIssuedAt: 1640995200,
    userAuthTime: 1640995200,
    userTokenVersion: "1.0",
    userPolicy: "B2C_1_signupsignin",
    userType: "CRM",
    userLastLogin: "2024-01-15T09:15:00Z",
    roles: [
      { _id: "role3", name: "Membership Officer", category: "CRM_OFFICERS" },
    ],
    isActive: true,
    createdBy: "admin",
    updatedBy: "admin",
    createdAt: "2024-01-02T00:00:00Z",
    updatedAt: "2024-01-15T09:15:00Z",
  },
  {
    _id: "user3",
    tenantId: "tenant1",
    userEmail: "mike.wilson@organization.com",
    userFirstName: "Mike",
    userLastName: "Wilson",
    userFullName: "Mike Wilson",
    userMobilePhone: "+1234567892",
    userMemberNumber: "MEM003",
    userMicrosoftId: "microsoft-id-003",
    userAuthProvider: "microsoft",
    userSubject: "sub-003",
    userAudience: "aud-003",
    userIssuer: "iss-003",
    userIssuedAt: 1640995200,
    userAuthTime: 1640995200,
    userTokenVersion: "1.0",
    userPolicy: "B2C_1_signupsignin",
    userType: "PORTAL",
    userLastLogin: "2024-01-15T08:45:00Z",
    roles: [{ _id: "role4", name: "Member", category: "PORTAL" }],
    isActive: true,
    createdBy: "system",
    updatedBy: "system",
    createdAt: "2024-01-03T00:00:00Z",
    updatedAt: "2024-01-15T08:45:00Z",
  },
  {
    _id: "user4",
    tenantId: "tenant1",
    userEmail: "sarah.johnson@organization.com",
    userFirstName: "Sarah",
    userLastName: "Johnson",
    userFullName: "Sarah Johnson",
    userMobilePhone: "+1234567893",
    userMemberNumber: "MEM004",
    userMicrosoftId: "microsoft-id-004",
    userAuthProvider: "microsoft",
    userSubject: "sub-004",
    userAudience: "aud-004",
    userIssuer: "iss-004",
    userIssuedAt: 1640995200,
    userAuthTime: 1640995200,
    userTokenVersion: "1.0",
    userPolicy: "B2C_1_signupsignin",
    userType: "CRM",
    userLastLogin: "2024-01-14T16:20:00Z",
    roles: [
      { _id: "role5", name: "Accounts Manager", category: "CRM_OFFICERS" },
      {
        _id: "role6",
        name: "Deputy General Secretary",
        category: "CRM_MANAGEMENT",
      },
    ],
    isActive: true,
    createdBy: "admin",
    updatedBy: "admin",
    createdAt: "2024-01-04T00:00:00Z",
    updatedAt: "2024-01-14T16:20:00Z",
  },
  {
    _id: "user5",
    tenantId: "tenant1",
    userEmail: "david.brown@organization.com",
    userFirstName: "David",
    userLastName: "Brown",
    userFullName: "David Brown",
    userMobilePhone: "+1234567894",
    userMemberNumber: "MEM005",
    userMicrosoftId: "microsoft-id-005",
    userAuthProvider: "microsoft",
    userSubject: "sub-005",
    userAudience: "aud-005",
    userIssuer: "iss-005",
    userIssuedAt: 1640995200,
    userAuthTime: 1640995200,
    userTokenVersion: "1.0",
    userPolicy: "B2C_1_signupsignin",
    userType: "CRM",
    userLastLogin: "2024-01-13T14:10:00Z",
    roles: [
      {
        _id: "role7",
        name: "Industrial Relations Officer",
        category: "CRM_OFFICERS",
      },
    ],
    isActive: false,
    createdBy: "admin",
    updatedBy: "admin",
    createdAt: "2024-01-05T00:00:00Z",
    updatedAt: "2024-01-13T14:10:00Z",
  },
  {
    _id: "user6",
    tenantId: "tenant2",
    userEmail: "lisa.garcia@audit.com",
    userFirstName: "Lisa",
    userLastName: "Garcia",
    userFullName: "Lisa Garcia",
    userMobilePhone: "+1234567895",
    userMemberNumber: "MEM006",
    userMicrosoftId: "microsoft-id-006",
    userAuthProvider: "microsoft",
    userSubject: "sub-006",
    userAudience: "aud-006",
    userIssuer: "iss-006",
    userIssuedAt: 1640995200,
    userAuthTime: 1640995200,
    userTokenVersion: "1.0",
    userPolicy: "B2C_1_signupsignin",
    userType: "CRM",
    userLastLogin: "2024-01-12T11:30:00Z",
    roles: [{ _id: "role8", name: "Read Only", category: "CRM_ACCESS" }],
    isActive: true,
    createdBy: "admin",
    updatedBy: "admin",
    createdAt: "2024-01-06T00:00:00Z",
    updatedAt: "2024-01-12T11:30:00Z",
  },
  {
    _id: "user7",
    tenantId: "tenant1",
    userEmail: "robert.taylor@organization.com",
    userFirstName: "Robert",
    userLastName: "Taylor",
    userFullName: "Robert Taylor",
    userMobilePhone: "+1234567896",
    userMemberNumber: "MEM007",
    userMicrosoftId: "microsoft-id-007",
    userAuthProvider: "microsoft",
    userSubject: "sub-007",
    userAudience: "aud-007",
    userIssuer: "iss-007",
    userIssuedAt: 1640995200,
    userAuthTime: 1640995200,
    userTokenVersion: "1.0",
    userPolicy: "B2C_1_signupsignin",
    userType: "CRM",
    userLastLogin: "2024-01-11T09:45:00Z",
    roles: [
      {
        _id: "role9",
        name: "Head Library Services",
        category: "CRM_SPECIALIZED",
      },
      { _id: "role10", name: "Librarian", category: "CRM_SPECIALIZED" },
    ],
    isActive: true,
    createdBy: "admin",
    updatedBy: "admin",
    createdAt: "2024-01-07T00:00:00Z",
    updatedAt: "2024-01-11T09:45:00Z",
  },
  {
    _id: "user8",
    tenantId: "tenant1",
    userEmail: "emma.davis@organization.com",
    userFirstName: "Emma",
    userLastName: "Davis",
    userFullName: "Emma Davis",
    userMobilePhone: "+1234567897",
    userMemberNumber: "MEM008",
    userMicrosoftId: "microsoft-id-008",
    userAuthProvider: "microsoft",
    userSubject: "sub-008",
    userAudience: "aud-008",
    userIssuer: "iss-008",
    userIssuedAt: 1640995200,
    userAuthTime: 1640995200,
    userTokenVersion: "1.0",
    userPolicy: "B2C_1_signupsignin",
    userType: "PORTAL",
    userLastLogin: "2024-01-10T15:20:00Z",
    roles: [{ _id: "role11", name: "Non-Member", category: "PORTAL" }],
    isActive: true,
    createdBy: "system",
    updatedBy: "system",
    createdAt: "2024-01-08T00:00:00Z",
    updatedAt: "2024-01-10T15:20:00Z",
  },
];

export const USER_TYPES = [
  { value: "all", label: "All User Types" },
  { value: "PORTAL", label: "Portal User" },
  { value: "CRM", label: "CRM User" },
];

export const USER_STATUSES = [
  { value: "all", label: "All Statuses" },
  { value: "active", label: "Active" },
  { value: "inactive", label: "Inactive" },
];

export const SAMPLE_TENANTS = [
  { id: "tenant1", name: "Main Organization" },
  { id: "tenant2", name: "Audit Department" },
  { id: "tenant3", name: "Finance Division" },
  { id: "tenant4", name: "HR Department" },
];

export const getAllUsersList = () => {
  return SAMPLE_USERS;
};

export const getTenantsList = () => {
  return SAMPLE_TENANTS;
};

export const getUserStatusBadge = (isActive) => {
  return isActive
    ? { status: "success", text: "Active" }
    : { status: "error", text: "Inactive" };
};

export const formatLastLogin = (lastLogin) => {
  if (!lastLogin) return "Never";
  const date = new Date(lastLogin);
  const now = new Date();
  const diffInHours = Math.floor((now - date) / (1000 * 60 * 60));

  if (diffInHours < 1) return "Just now";
  if (diffInHours < 24) return `${diffInHours}h ago`;
  if (diffInHours < 168) return `${Math.floor(diffInHours / 24)}d ago`;
  return date.toLocaleDateString();
};
