import React from "react";
import { useTableColumns } from "../../context/TableColumnsContext ";
import TableComponent from "../../component/common/TableComponent";
function ProfileSummary() {
  // const{gridData} = useTableColumns()
  const gridData = [
    {
      key: "1",
      regNo: "M0001",
      fullName: "John Smith",
      email: "john.smith@email.com",
      mobileNo: "0871234567",
      dob: "15/03/1985",
      gender: "Male",
      address: "12 Main Street, Dublin",
      notAtAddress: "No",
      membershipCategory: "General",
      station: "St. James Hospital",
      branch: "Dublin Central",
      region: "Leinster",
      rank: "Nurse",
      sectionPrimary: "Emergency",
      dateRetired: "",
      pensionNo: "",
      payrollNo: "P001",
      nmbiNo: "NMBI12345",
      speciality: "Emergency Care",
      anotherUnionMember: "No",
      consent: "Yes",
      incomeProtection: "Yes",
      inmoRewards: "Yes",
      partnerConsent: "Yes",
      grade: "Lead",
    },
    {
      key: "2",
      regNo: "M0002",
      fullName: "Mary Johnson",
      email: "mary.johnson@email.com",
      mobileNo: "0872345678",
      dob: "22/07/1990",
      gender: "Female",
      address: "45 Oak Avenue, Cork",
      notAtAddress: "No",
      membershipCategory: "Postgraduate Student",
      station: "Cork University Hospital",
      branch: "Cork South",
      region: "Munster",
      rank: "Student Nurse",
      sectionPrimary: "Pediatrics",
      grade: "Junior",
      dateRetired: "",
      pensionNo: "",
      payrollNo: "P002",
      nmbiNo: "NMBI23456",
      speciality: "Pediatrics",
      anotherUnionMember: "No",
      consent: "Yes",
      incomeProtection: "No",
      inmoRewards: "Yes",
      partnerConsent: "No",
    },
    {
      key: "3",
      regNo: "M0003",
      fullName: "Patrick O’Brien",
      email: "patrick.obrien@email.com",
      mobileNo: "0873456789",
      dob: "02/11/1972",
      gender: "Male",
      address: "7 Park Lane, Galway",
      notAtAddress: "No",
      grade: "Senior",
      membershipCategory: "Affiliate Non-Practicing",
      station: "Galway Clinic",
      branch: "Galway North",
      region: "Connacht",
      rank: "Consultant",
      sectionPrimary: "Cardiology",
      dateRetired: "01/12/2023",
      pensionNo: "PENS123",
      payrollNo: "P003",
      nmbiNo: "NMBI34567",
      speciality: "Cardiology",
      anotherUnionMember: "Yes",
      consent: "Yes",
      incomeProtection: "Yes",
      inmoRewards: "No",
      partnerConsent: "Yes",
    },
    {
      key: "4",
      regNo: "M0004",
      fullName: "Siobhan Murphy",
      email: "siobhan.murphy@email.com",
      mobileNo: "0874567890",
      dob: "12/05/1988",
      gender: "Female",
      grade: "Junior",
      address: "22 River Road, Limerick",
      notAtAddress: "Yes",
      membershipCategory: "General",
      station: "University Hospital Limerick",
      branch: "Limerick City",
      region: "Munster",
      rank: "Nurse",
      sectionPrimary: "Maternity",
      dateRetired: "",
      pensionNo: "",
      payrollNo: "P004",
      nmbiNo: "NMBI45678",
      speciality: "Midwifery",
      anotherUnionMember: "No",
      consent: "Yes",
      incomeProtection: "Yes",
      inmoRewards: "Yes",
      partnerConsent: "Yes",
    },
    {
      key: "5",
      regNo: "M0005",
      fullName: "Michael Kelly",
      email: "michael.kelly@email.com",
      mobileNo: "0875678901",
      dob: "30/09/1995",
      gender: "Male",
      address: "88 Hill View, Waterford",
      grade: "Senior",
      notAtAddress: "No",
      membershipCategory: "Graduate",
      station: "Waterford Regional Hospital",
      branch: "Waterford East",
      region: "Munster",
      rank: "Junior Doctor",
      sectionPrimary: "Oncology",
      dateRetired: "",
      pensionNo: "",
      payrollNo: "P005",
      nmbiNo: "NMBI56789",
      speciality: "Oncology",
      anotherUnionMember: "No",
      consent: "Yes",
      incomeProtection: "No",
      inmoRewards: "Yes",
      partnerConsent: "No",
    },
    {
      key: "6",
      regNo: "M0006",
      fullName: "Emma Walsh",
      email: "emma.walsh@email.com",
      mobileNo: "0876789012",
      dob: "11/04/1992",
      gender: "Female",
      address: "10 Castle Street, Kilkenny",
      notAtAddress: "No",
      membershipCategory: "General",
      station: "St. Luke’s Hospital",
      branch: "Kilkenny City",
      region: "Leinster",
      rank: "Nurse",
      sectionPrimary: "Orthopedics",
      dateRetired: "",
      pensionNo: "",
      payrollNo: "P006",
      nmbiNo: "NMBI67890",
      speciality: "Orthopedic Nursing",
      anotherUnionMember: "No",
      consent: "Yes",
      incomeProtection: "Yes",
      inmoRewards: "No",
      partnerConsent: "Yes",
    },
    {
      key: "7",
      regNo: "M0007",
      fullName: "Brian Doyle",
      email: "brian.doyle@email.com",
      mobileNo: "0877890123",
      dob: "05/06/1980",
      gender: "Male",
      address: "55 Harbour View, Wexford",
      notAtAddress: "No",
      membershipCategory: "General",
      station: "Wexford General Hospital",
      branch: "Wexford Town",
      region: "Leinster",
      rank: "Senior Nurse",
      sectionPrimary: "Surgery",
      dateRetired: "",
      pensionNo: "",
      payrollNo: "P007",
      nmbiNo: "NMBI78901",
      speciality: "Surgical Nursing",
      anotherUnionMember: "No",
      consent: "Yes",
      incomeProtection: "Yes",
      inmoRewards: "Yes",
      partnerConsent: "No",
    },

    // ...continue in the same pattern until key: "20"
  ];

  return (
    <div className="" style={{ width: "100%" }}>
      <TableComponent
        data={gridData}
        screenName="Profile"
        redirect="/Details"
      />
    </div>
  );
}
export default ProfileSummary;
