name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "REACT_APP_CLIENT_ID=${{ secrets.REACT_APP_CLIENT_ID }}" >> $GITHUB_ENV
          echo "REACT_APP_TENANT_ID=${{ secrets.REACT_APP_TENANT_ID }}" >> $GITHUB_ENV
          echo "REACT_APP_CLIENT_ID_OUTLOOK=${{ secrets.REACT_APP_CLIENT_ID_OUTLOOK }}" >> $GITHUB_ENV
          echo "REACT_APP_TENANT_ID_OUTLOOK=${{ secrets.REACT_APP_TENANT_ID_OUTLOOK }}" >> $GITHUB_ENV
          echo "REACT_APP_REDIRECT_URI=${{ secrets.REACT_APP_REDIRECT_URI }}" >> $GITHUB_ENV
          echo "REACT_APP_BASE_URL_DEV=${{ secrets.REACT_APP_BASE_URL_DEV }}" >> $GITHUB_ENV

      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_SKY_09F929A10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "build"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_SKY_09F929A10 }}
          action: "close"
