name: Build and deploy Node.js app to Azure Web App - ProjectShellCRM

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Build project (CI=false, increased memory)
        run: |
          CI=false node --max-old-space-size=8192 $(which npm) run build --if-present

      - name: Run tests (if present)
        run: npm run test --if-present

      - name: Zip build folder (contents only)
        run: |
          cd build
          zip -r ../release.zip .

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1F079DAA17E54BA5A88FA2393750C3F2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F6B1D39DE6C1430D92EA23FE95510021 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B9BB435DFBC94FFF8073519DF27F5C9C }}

      - name: Wait before deploy
        run: sleep 15

      - name: Try deploy to Azure Web App (with retry)
        id: deploy-to-webapp
        run: |
          for i in {1..3}; do
            echo "Deployment attempt #$i"
            npx @azure/webapps-deploy --app-name 'ProjectShellCRM' --package release.zip && break || sleep 15
          done
