name: Build and deploy Node.js app to Azure Web App - ProjectShellApp

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project with increased memory limit
      - name: Build project with increased memory limit
        run: |
          node --max-old-space-size=8192 $(which npm) run build --verbose

      # Optionally, check for memory-related errors
      - name: Check for memory issues
        run: dmesg | grep -i 'out of memory'

      - name: npm test (optional)
        run: npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_49C312A1E05D415A81E295AF642B0578 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2C993618D2234ABB83AB827383DC5A62 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_907B7AA8684242F288B17F09A1F17770 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ProjectShellApp'
          slot-name: 'Production'
          package: .
