import React from 'react'
import TableComponent from '../../component/common/TableComponent'

function CorrespondencesSummary() {
  const correspondenceDetailsDataSource = [
    {
      key: "1",
      correspondenceID: "C001",
      regNo: "45217A",
      forename: "Jack",
      surname: "Smith",
      methodOfContact: "Call",
      dateOfContact: "2024-10-01",
      duration: "10 mins",
      details: "Discussed details of the upcoming project.",
      followUpNeeded: "Yes",
      followUpDate: "2024-10-15",
      status: "Completed",
      nextStep: "Schedule next meeting.",
    },
    {
      key: "2",
      correspondenceID: "C002",
      regNo: "45218B",
      forename: "John",
      surname: "Doe",
      methodOfContact: "Email",
      dateOfContact: "2024-10-05",
      duration: "N/A",
      details: "Sent the report for review.",
      followUpNeeded: "No",
      followUpDate: "N/A",
      status: "Pending",
      nextStep: "Wait for feedback.",
    },
    {
      key: "3",
      correspondenceID: "C003",
      regNo: "45219C",
      forename: "Alice",
      surname: "Brown",
      methodOfContact: "Letter",
      dateOfContact: "2024-10-10",
      duration: "N/A",
      details: "Sent letter requesting additional information.",
      followUpNeeded: "Yes",
      followUpDate: "2024-10-20",
      status: "In Progress",
      nextStep: "Review received documents.",
    },
    {
      key: "4",
      correspondenceID: "C004",
      regNo: "45220D",
      forename: "Charlie",
      surname: "Johnson",
      methodOfContact: "Email",
      dateOfContact: "2024-10-12",
      duration: "15 mins",
      details: "Discussed case updates and future action.",
      followUpNeeded: "Yes",
      followUpDate: "2024-10-22",
      status: "Completed",
      nextStep: "Schedule follow-up meeting.",
    },
    {
      key: "5",
      correspondenceID: "C005",
      regNo: "45221E",
      forename: "Emma",
      surname: "Wilson",
      methodOfContact: "Call",
      dateOfContact: "2024-10-15",
      duration: "20 mins",
      details: "Follow-up on missing documents for investigation.",
      followUpNeeded: "No",
      followUpDate: "N/A",
      status: "Pending",
      nextStep: "Await document submission.",
    },
    {
      key: "6",
      correspondenceID: "C006",
      regNo: "45222F",
      forename: "Liam",
      surname: "Davis",
      methodOfContact: "Letter",
      dateOfContact: "2024-10-17",
      duration: "N/A",
      details: "Official letter sent requesting further details.",
      followUpNeeded: "Yes",
      followUpDate: "2024-10-25",
      status: "In Progress",
      nextStep: "Evaluate response.",
    },
    {
      key: "7",
      correspondenceID: "C007",
      regNo: "45223G",
      forename: "Olivia",
      surname: "Taylor",
      methodOfContact: "Email",
      dateOfContact: "2024-10-18",
      duration: "5 mins",
      details: "Follow-up email for status update on investigation.",
      followUpNeeded: "No",
      followUpDate: "N/A",
      status: "Completed",
      nextStep: "None.",
    },
    {
      key: "8",
      correspondenceID: "C008",
      regNo: "45224H",
      forename: "Noah",
      surname: "Anderson",
      methodOfContact: "Call",
      dateOfContact: "2024-10-20",
      duration: "10 mins",
      details: "Initial call for scheduling an interview.",
      followUpNeeded: "Yes",
      followUpDate: "2024-10-30",
      status: "Pending",
      nextStep: "Prepare for interview.",
    },
    {
      key: "9",
      correspondenceID: "C009",
      regNo: "45225I",
      forename: "Sophia",
      surname: "Martinez",
      methodOfContact: "Letter",
      dateOfContact: "2024-10-22",
      duration: "N/A",
      details: "Sent official letter regarding officer evaluation.",
      followUpNeeded: "No",
      followUpDate: "N/A",
      status: "In Progress",
      nextStep: "Review results of evaluation.",
    },
    {
      key: "10",
      correspondenceID: "C010",
      regNo: "45226J",
      forename: "James",
      surname: "Moore",
      methodOfContact: "Email",
      dateOfContact: "2024-10-25",
      duration: "10 mins",
      details: "Urgent email regarding case closure and action plan.",
      followUpNeeded: "Yes",
      followUpDate: "2024-10-30",
      status: "Completed",
      nextStep: "Finalize case closure.",
    },
  ];
  
  return (
    <div>
     <TableComponent   screenName="Correspondence" data={correspondenceDetailsDataSource} redirect="/Details" />
      
    </div>
  )
}

export default CorrespondencesSummary